"""Closed vocabularies from the specification.

Only genuinely closed sets live here. Open-world vocabularies -- mark open
codes, ontology concept names, cross-strategy relation types -- are free
strings by design (constitution rule 2), and forcing them into an enum is the
category blindness the system exists to avoid.
"""

from __future__ import annotations

from enum import StrEnum


class EvidenceLabel(StrEnum):
    SOURCE_EXPLICIT = "SOURCE_EXPLICIT"
    SOURCE_IMPLICIT = "SOURCE_IMPLICIT"
    PRACTITIONER_HEURISTIC = "PRACTITIONER_HEURISTIC"
    BACKTEST_REPORTED = "BACKTEST_REPORTED"
    EXPERIMENT_REPORTED = "EXPERIMENT_REPORTED"
    THEORETICAL_CLAIM = "THEORETICAL_CLAIM"
    SECONDARY_SUMMARY = "SECONDARY_SUMMARY"
    MODEL_INTERPRETATION = "MODEL_INTERPRETATION"
    VERIFIED_ENTAILMENT = "VERIFIED_ENTAILMENT"
    V8_DESIGN_INFERENCE = "V8_DESIGN_INFERENCE"
    OPEN_QUESTION = "OPEN_QUESTION"
    REJECTED_EXTRACTION = "REJECTED_EXTRACTION"


class EpistemicAct(StrEnum):
    OBSERVED = "OBSERVED"
    ANECDOTAL = "ANECDOTAL"
    PRESCRIPTIVE = "PRESCRIPTIVE"
    CAUSAL_CLAIM = "CAUSAL_CLAIM"
    CORRELATIONAL_CLAIM = "CORRELATIONAL_CLAIM"
    THEORETICAL = "THEORETICAL"
    BACKTEST_REPORTED = "BACKTEST_REPORTED"
    EXPERIMENTAL = "EXPERIMENTAL"
    SECONDARY_SUMMARY = "SECONDARY_SUMMARY"
    DEFINITIONAL = "DEFINITIONAL"
    COUNTEREXAMPLE = "COUNTEREXAMPLE"
    RETRACTION_OR_QUALIFICATION = "RETRACTION_OR_QUALIFICATION"


class Modality(StrEnum):
    """Ordered weakest to strongest; the verifier rejects upgrades."""

    MAY = "MAY"
    SOMETIMES = "SOMETIMES"
    OFTEN = "OFTEN"
    USUALLY = "USUALLY"
    ALWAYS = "ALWAYS"
    MUST = "MUST"


MODALITY_RANK: dict[str, int] = {
    Modality.MAY: 0,
    Modality.SOMETIMES: 1,
    Modality.OFTEN: 2,
    Modality.USUALLY: 3,
    Modality.ALWAYS: 4,
    Modality.MUST: 5,
}


class LineageRelation(StrEnum):
    CITES = "CITES"
    DERIVES_FROM = "DERIVES_FROM"
    REPHRASES = "REPHRASES"
    SAME_AUTHOR_LINEAGE = "SAME_AUTHOR_LINEAGE"
    SAME_DATASET = "SAME_DATASET"
    SAME_HISTORICAL_EPISODE = "SAME_HISTORICAL_EPISODE"
    SAME_EDITION_FAMILY = "SAME_EDITION_FAMILY"
    POSSIBLE_COPY = "POSSIBLE_COPY"
    TRANSLATION_OF = "TRANSLATION_OF"
    COMMENTARY_ON = "COMMENTARY_ON"


class DiscoveryChannel(StrEnum):
    SECTION_LLM = "SECTION_LLM"
    CHAPTER_SYNTHESIS = "CHAPTER_SYNTHESIS"
    LEXICAL_RARITY = "LEXICAL_RARITY"
    EMBEDDING_OUTLIER = "EMBEDDING_OUTLIER"
    CROSS_REFERENCE = "CROSS_REFERENCE"
    RANDOM_AUDIT = "RANDOM_AUDIT"
    CONTRADICTION = "CONTRADICTION"


class RereadTrigger(StrEnum):
    CONDITION_MISSING = "CONDITION_MISSING"
    DEFINITION_MISSING = "DEFINITION_MISSING"
    CROSS_SECTION_DEPENDENCY = "CROSS_SECTION_DEPENDENCY"
    CHAPTER_ARGUMENT_INCOMPLETE = "CHAPTER_ARGUMENT_INCOMPLETE"
    LATER_QUALIFICATION_POSSIBLE = "LATER_QUALIFICATION_POSSIBLE"
    EXAMPLE_RULE_MISMATCH = "EXAMPLE_RULE_MISMATCH"
    CONTRADICTION_UNRESOLVED = "CONTRADICTION_UNRESOLVED"
    SOURCE_LINEAGE_UNCLEAR = "SOURCE_LINEAGE_UNCLEAR"
    TABLE_OR_FIGURE_REQUIRED = "TABLE_OR_FIGURE_REQUIRED"
    VERIFIER_SCOPE_FAILURE = "VERIFIER_SCOPE_FAILURE"
    MODALITY_UNCLEAR = "MODALITY_UNCLEAR"
    V8_HIGH_IMPACT_REQUIRES_CONTEXT = "V8_HIGH_IMPACT_REQUIRES_CONTEXT"
    RANDOM_AUDIT = "RANDOM_AUDIT"
    HUMAN_REVIEW_REQUEST = "HUMAN_REVIEW_REQUEST"


class ReadMode(StrEnum):
    SPAN_ONLY = "SPAN_ONLY"
    LOCAL_WINDOW = "LOCAL_WINDOW"
    CONTIGUOUS_SECTION = "CONTIGUOUS_SECTION"
    MULTI_SECTION = "MULTI_SECTION"
    CHAPTER_READ = "CHAPTER_READ"
    CROSS_SOURCE = "CROSS_SOURCE"
    FIGURE_TABLE_READ = "FIGURE_TABLE_READ"


class ReadPurpose(StrEnum):
    NAVIGATION = "NAVIGATION"
    MARKING = "MARKING"
    REREAD = "REREAD"
    VERIFICATION = "VERIFICATION"


class FindingStatus(StrEnum):
    VERIFIED = "VERIFIED"
    PROVISIONAL = "PROVISIONAL"
    CONTESTED = "CONTESTED"
    REJECTED = "REJECTED"


class RunStatus(StrEnum):
    """Terminal run statuses.

    COMPLETE is epistemic. Every other status is operational, and no resource
    condition may ever map to COMPLETE (constitution rule 16).
    """

    COMPLETE = "COMPLETE"
    PAUSED_RESOURCE_LIMIT = "PAUSED_RESOURCE_LIMIT"
    PAUSED_RATE_LIMIT = "PAUSED_RATE_LIMIT"
    PAUSED_HUMAN_REVIEW = "PAUSED_HUMAN_REVIEW"
    BLOCKED_MISSING_SOURCE = "BLOCKED_MISSING_SOURCE"
    BLOCKED_VERIFICATION_FAILURE = "BLOCKED_VERIFICATION_FAILURE"
    FAILED_PIPELINE = "FAILED_PIPELINE"
    RUNNING = "RUNNING"


RESOURCE_STATUSES = frozenset(
    {RunStatus.PAUSED_RESOURCE_LIMIT, RunStatus.PAUSED_RATE_LIMIT}
)


class QueueName(StrEnum):
    INGEST = "INGEST"
    NAVIGATE = "NAVIGATE"
    MARK_SECTION = "MARK_SECTION"
    SYNTHESIZE_CHAPTER = "SYNTHESIZE_CHAPTER"
    SCAN_RARITY = "SCAN_RARITY"
    SCAN_OUTLIER = "SCAN_OUTLIER"
    AUDIT_RANDOM = "AUDIT_RANDOM"
    RECONSTRUCT_CONTEXT = "RECONSTRUCT_CONTEXT"
    EXTRACT_CLAIM = "EXTRACT_CLAIM"
    ALIGN_EVIDENCE = "ALIGN_EVIDENCE"
    VERIFY_CLAIM = "VERIFY_CLAIM"
    ANALYZE_LINEAGE = "ANALYZE_LINEAGE"
    ANNOTATE_ONTOLOGY = "ANNOTATE_ONTOLOGY"
    MAP_V8_IMPACT = "MAP_V8_IMPACT"
    HUMAN_ADJUDICATE = "HUMAN_ADJUDICATE"


class PriorityClass(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    NORMAL = "NORMAL"
    AUDIT = "AUDIT"
    BACKGROUND = "BACKGROUND"


class ModelTier(StrEnum):
    LOCAL = "LOCAL"
    SMALL = "SMALL"
    MEDIUM = "MEDIUM"
    STRONG = "STRONG"
    HUMAN = "HUMAN"


class OntologyOperation(StrEnum):
    ADD_CONCEPT = "ADD_CONCEPT"
    ADD_RELATION = "ADD_RELATION"
    MERGE_CONCEPTS = "MERGE_CONCEPTS"
    SPLIT_CONCEPT = "SPLIT_CONCEPT"
    RENAME_CONCEPT = "RENAME_CONCEPT"
    ADD_CONSTRAINT = "ADD_CONSTRAINT"
    NARROW_DEFINITION = "NARROW_DEFINITION"
    DEPRECATE_CONCEPT = "DEPRECATE_CONCEPT"
    CHALLENGE_ASSUMPTION = "CHALLENGE_ASSUMPTION"


class ImpactRelation(StrEnum):
    SUPPORTS = "SUPPORTS"
    CHALLENGES = "CHALLENGES"
    NARROWS = "NARROWS"
    REQUIRES_EXTENSION = "REQUIRES_EXTENSION"
    REVEALS_MISSING_VARIABLE = "REVEALS_MISSING_VARIABLE"
    REVEALS_UNTESTED_INTERACTION = "REVEALS_UNTESTED_INTERACTION"
    REVEALS_INVALID_ABSTRACTION = "REVEALS_INVALID_ABSTRACTION"
    SUGGESTS_NEW_COMPONENT = "SUGGESTS_NEW_COMPONENT"
    SUGGESTS_COMPONENT_REMOVAL = "SUGGESTS_COMPONENT_REMOVAL"
    NO_IMPACT = "NO_IMPACT"


class AssumptionStatus(StrEnum):
    LOCKED_INVARIANT = "LOCKED_INVARIANT"
    PROVISIONAL_DECISION = "PROVISIONAL_DECISION"
    OPEN_QUESTION = "OPEN_QUESTION"


class ProposalKind(StrEnum):
    EXPERT_HYPOTHESIS = "EXPERT_HYPOTHESIS"
    STRATEGY_FAMILY = "STRATEGY_FAMILY"
    POSITION_EVALUATION = "POSITION_EVALUATION"
    RISK_RULE = "RISK_RULE"
    MARKETSTATE_OBSERVABLE = "MARKETSTATE_OBSERVABLE"
    CROSS_STRATEGY_INTERACTION = "CROSS_STRATEGY_INTERACTION"
    CANDIDATE_LIFECYCLE_EXTENSION = "CANDIDATE_LIFECYCLE_EXTENSION"
    EXECUTION_RESEARCH_QUESTION = "EXECUTION_RESEARCH_QUESTION"
    SIMULATION_FIDELITY_REQUIREMENT = "SIMULATION_FIDELITY_REQUIREMENT"
    ARCHITECTURE_CHALLENGE = "ARCHITECTURE_CHALLENGE"
    EXPERIMENT_PREREGISTRATION = "EXPERIMENT_PREREGISTRATION"
    NO_CURRENT_V8_COMPILATION = "NO_CURRENT_V8_COMPILATION"


class NodeType(StrEnum):
    DOCUMENT = "DOCUMENT"
    CHAPTER = "CHAPTER"
    SECTION = "SECTION"
    SUBSECTION = "SUBSECTION"
    PARAGRAPH = "PARAGRAPH"
    TABLE = "TABLE"
    FIGURE = "FIGURE"
    NOTE = "NOTE"


class MarkStatus(StrEnum):
    MARKED = "MARKED"
    PROMOTED = "PROMOTED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class TaskStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    PARTIALLY_RESOLVED = "PARTIALLY_RESOLVED"
    UNRESOLVABLE_IN_SOURCE = "UNRESOLVABLE_IN_SOURCE"
    REQUIRES_EXTERNAL_SOURCE = "REQUIRES_EXTERNAL_SOURCE"
    DUPLICATE_QUESTION = "DUPLICATE_QUESTION"
    ABANDONED_LOW_VALUE = "ABANDONED_LOW_VALUE"
    DEFERRED = "DEFERRED"
    FAILED = "FAILED"


# Preregistered value rubric (spec: Weighted Discovery Utility). Fixed ahead of
# any run so findings cannot be scored favourably in hindsight.
FINDING_VALUE_RUBRIC: dict[int, str] = {
    1: "Additional example of a known concept.",
    2: "New boundary condition or exception.",
    3: "New relation among known concepts.",
    4: "New concept or observable requirement.",
    5: "Credible challenge to a V8 assumption.",
    6: "Finding that could require architecture change.",
}
