#!/usr/bin/env python3
"""P4 v2.3 A2.2 — LLM approval record for mined name candidates.

This file records, for each candidate mined by A2.1, the approval decision and
(where approved) the source-explicit spelling and the canonical_method_id /
method_class / parent_behavior_id to add in A2.3. Decisions were made by
reviewing each candidate's literal occurrence in the 101 books' p4_gate_input
anchor_text (allowed: A2 mining operates on anchor_text). Names not present
verbatim, or not a named method, are rejected. This is the LLM-approval step;
the decision set is deterministic going forward.
"""
# Approved: dict candidate -> {mid, name_in_source, parent, mclass}
APPROVED = {
    # --- directive-listed missing canonical families, confirmed present ---
    'ichimoku': dict(mid='indicator_ichimoku', name='Ichimoku',
                     parent='trend_following_channel', mclass='indicator_method'),
    'tenkan': dict(mid='indicator_ichimoku_tenkan', name='Tenkan',
                   parent='trend_following_channel', mclass='indicator_method'),
    'kijun': dict(mid='indicator_ichimoku_kijun', name='Kijun',
                  parent='trend_following_channel', mclass='indicator_method'),
    'kagi': dict(mid='chart_kagi', name='Kagi',
                 parent='trend_following_channel', mclass='chart_pattern'),
    'renko': dict(mid='chart_renko', name='Renko',
                  parent='trend_following_channel', mclass='chart_pattern'),
    'commitments of traders': dict(mid='indicator_commitments_of_traders', name='Commitment of Traders',
                                    parent='volume_confirmed_breakout', mclass='indicator_method'),
    'vwap': dict(mid='indicator_vwap', name='VWAP',
                 parent='mean_reversion_band', mclass='indicator_method'),
    'atr': dict(mid='indicator_atr', name='ATR',
                parent='volatility_breakout', mclass='indicator_method'),
    'williams %R': dict(mid='indicator_williams_r', name='Williams %R',
                        parent='mean_reversion_band', mclass='indicator_method'),
    'cci': dict(mid='indicator_cci', name='CCI',
                parent='mean_reversion_band', mclass='indicator_method'),
    'keltner': dict(mid='indicator_keltner_channel', name='Keltner Channel',
                    parent='mean_reversion_band', mclass='indicator_method'),
    'elliott wave': dict(mid='indicator_elliott_wave', name='Elliott Wave',
                         parent='trend_following_channel', mclass='indicator_method'),
    'gann': dict(mid='indicator_gann', name='Gann',
                 parent='support_resistance_bounce', mclass='indicator_method'),
    'market profile': dict(mid='indicator_market_profile', name='Market Profile',
                           parent='volume_confirmed_breakout', mclass='indicator_method'),
    # --- additional genuinely-named methods confirmed in source ---
    'vfi': dict(mid='indicator_volume_flow', name='Volume Flow Indicator',
                parent='volume_confirmed_breakout', mclass='indicator_method'),
    'obv': dict(mid='indicator_on_balance_volume', name='OBV',
                parent='volume_confirmed_breakout', mclass='indicator_method'),
    'dmi': dict(mid='indicator_dmi', name='DMI',
                parent='trend_continuation_pullback', mclass='indicator_method'),
    'fan lines': dict(mid='indicator_gann_fan_lines', name='Fan Lines',
                      parent='support_resistance_bounce', mclass='indicator_method'),
    'half-mast': dict(mid='chart_half_mast', name='Half-mast',
                      parent='trend_continuation_pullback', mclass='chart_pattern'),
    'kiss': dict(mid='strategy_kiss', name='KISS',
                 parent='mean_reversion_band', mclass='other'),
    'spring': dict(mid='level_spring', name='Spring',
                   parent='support_resistance_bounce', mclass='level_method'),
    'broadening top': dict(mid='chart_broadening_top', name='Broadening Top',
                           parent='volatility_breakout', mclass='chart_pattern'),
    'one-day reversal': dict(mid='candlestick_one_day_reversal', name='One-Day Reversal',
                             parent='candlestick_reversal_pattern', mclass='candlestick_single_line'),
    'busted': dict(mid='pa_busted', name='Busted',
                   parent='failed_breakout_reentry', mclass='other'),
    'rs-macd': dict(mid='indicator_rs_macd', name='RS-MACD',
                    parent='momentum_divergence_reversal', mclass='indicator_method'),
    'comas': dict(mid='indicator_comas', name='COMAS',
                  parent='mean_reversion_band', mclass='indicator_method'),
    'atm tsb': dict(mid='indicator_atm_tsb', name='ATM TSB',
                    parent='mean_reversion_band', mclass='indicator_method'),
    'ges': dict(mid='chart_ges', name='GES',
                parent='breakout_retest', mclass='chart_pattern'),
    'jdk rs-ratio': dict(mid='indicator_jdk_rs_ratio', name='JdK RS-Ratio',
                         parent='momentum_divergence_reversal', mclass='indicator_method'),
    'ribbon study': dict(mid='indicator_ribbon_study', name='Ribbon Study',
                         parent='trend_following_channel', mclass='indicator_method'),
    'dual moving average': dict(mid='strategy_dual_moving_average', name='Dual Moving Average',
                                parent='trend_continuation_pullback', mclass='other'),
    'expanded flat': dict(mid='chart_expanded_flat', name='Expanded Flat',
                          parent='trend_continuation_pullback', mclass='chart_pattern'),
    'zigzag': dict(mid='chart_zigzag', name='Zigzag',
                   parent='trend_continuation_pullback', mclass='chart_pattern'),
    'dma': dict(mid='indicator_dma', name='DMA',
                parent='trend_continuation_pullback', mclass='indicator_method'),
    'pinocchio': dict(mid='pa_pinocchio', name='Pinocchio',
                      parent='liquidity_sweep_reclaim', mclass='other'),
    'impulse': dict(mid='chart_impulse', name='Impulse',
                    parent='trend_following_channel', mclass='chart_pattern'),
}

# Rejected: candidate -> reason (noise / not a named method / already covered)
REJECTED = {
    'MACD': 'already in catalog (indicator_macd)',
    'RSI': 'already covered by generic + RSI BAMM; RSI alone is an indicator parameter, not a distinct named method',
    'Momentum': 'generic term, not a named method',
    'Buddha': 'no confirmed named-method usage in gate input',
    'Risk\\nThe': 'anchor_text truncation noise',
    'Shoulders Top': 'head-and-shoulders variant, already covered by chart_head_shoulders',
    'Signal': 'generic',
    'Stalled': 'descriptive verb, not a named method',
    'Anti': 'noise fragment',
    'Dark': 'noise fragment (Dark Cloud Cover already in catalog)',
    'Piercing': 'already in catalog (candlestick_piercing)',
    'Bollinger Band': 'already in catalog (indicator_bollinger_bands)',
    'Climax': 'generic',
    'Confirmation\\nThe': 'truncation noise',
    'Consolidation': 'generic',
    'Crowd Behavior\\nThe Directional': 'truncation noise',
    'Decline': 'generic',
    'Deliberation': 'already in catalog (candlestick_deliberation)',
    'Equity': 'generic',
    'Flat': 'generic (Elliott flat covered by Expanded Flat)',
    'Holy Grail': 'idiom, not a method',
    'Market\\nBear Market\\nTall': 'truncation noise',
    'Narrow': 'generic',
    'QQQ': 'ticker, not a method',
    'Reversal': 'generic',
    'Short': 'generic',
    'Stochastics': 'already in catalog (indicator_stochastic)',
    'A-B-C': 'generic Elliott correction, no distinct method',
    'AADB': 'unverified acronym',
    'ADX line shown in Figure': 'ADX already in catalog; trailing text noise',
    'ADX that tells you when a marke': 'truncation noise',
    'AND BEARS POWER\\nThis': 'truncation noise',
    'ATR Channel Breakout': 'covered by indicator_atr',
    'Adam': 'already in catalog (chart_adam_eve)',
    'Aharami': 'misspelling of harami, already in catalog',
    'Ahigh': 'truncation noise',
    'An RSI': 'truncation noise',
    'Answer\\nHer': 'truncation noise',
    'August': 'month, noise',
    'Basic Elliott': 'covered by indicator_elliott_wave',
    'Bollinger\\nBands': 'already in catalog',
    'Bollinger Breakout\\nThis': 'already in catalog; truncation noise',
    'Bollinger bands': 'already in catalog',
    'Boy Plunger for nothing': 'noise',
    'Breakdown\\nMarket Type\\nThis': 'truncation noise',
    'Broken': 'generic',
    'Bruce': 'proper name, noise',
    'Bullish\\nThis': 'truncation noise',
    'CTAs for': 'truncation noise',
    'Central Bank Agreement on Gold': 'not a method',
    'Channel': 'generic',
    'Characteristics This': 'truncation noise',
    'Chicago': 'place, noise',
    'Complex': 'generic',
    'Congestion': 'generic',
    'Continuation': 'generic',
    'Crab': 'already in catalog (harmonic_crab)',
    'Crossing': 'generic',
    'D extension': 'harmonic extension, no distinct named method',
    'DJIA': 'index, noise',
    'DeTrended OscI': 'garbled, unverified',
    'Diamonds': 'chart pattern but not confirmed as named method in gate input',
    'Disciplining Device\\nThe': 'truncation noise',
    'Discovering': 'generic',
    'Divergence': 'generic',
    'Doji lines': 'already in catalog (candlestick_doji)',
    'Donchian Trend': 'already in catalog (indicator_donchian)',
    'Earnings\\nBusted': 'truncation noise',
    'Efficient Market': 'theory, not a method',
    'Eve': 'already in catalog (chart_adam_eve)',
    'FTSE': 'index, noise',
    'Fib': 'already in catalog (indicator_fibonacci_retracement)',
    'Fibonacci Retracement': 'already in catalog',
    'Future': 'generic',
    'Graham-and-Doddsville': 'author reference, not a method',
    'HPI': 'index, noise',
    'Harvey and said': 'truncation noise',
    'Head-and-Shoulders Top': 'already in catalog (chart_head_shoulders)',
    'Horn Tops': 'chart pattern, not confirmed as distinct named method',
    'IHS': 'head-and-shoulders inverse, already covered',
    'In-Neck\\nIn-neck': 'already in catalog (candlestick_in_neck_line)',
    'Independence Day': 'holiday, noise',
    'Inverted\\nThe': 'truncation noise',
    'Investors Intelligence for trac': 'truncation noise',
    'Its': 'pronoun, noise',
    'January Effect': 'seasonal phenomenon, not a trading method',
    'June': 'month, noise',
    'LINE\\nThis': 'truncation noise',
    'Linear': 'generic',
    'Loss Aversion': 'behavioral bias, not a method',
    'Lower': 'generic',
    'Marabozu': 'misspelling of marubozu, not in catalog yet but candlestick family; kept as observed mention',
    'Market Conditions\\nThis': 'truncation noise',
    'Mechanica': 'garbled, unverified',
    'MetaStock': 'software, not a method',
    'Moving Average Convergence Divergence': 'already in catalog (indicator_macd)',
    'OEX': 'index, noise',
    'ON THE PATTERNS\\nAnother': 'truncation noise',
    'ONLY ONE METHOD\\nWhich': 'truncation noise',
    'On-neck': 'already in catalog (candlestick_on_neck_line)',
    'OneCoin was met with much inter': 'truncation noise',
    'Oscillator Rec': 'garbled, unverified',
    'Overriding': 'generic',
    'Overtrading\\nSome': 'truncation noise',
    'PATTERN\\nThe Gartley': 'already in catalog (harmonic_gartley)',
    'Parabolic': 'already handled (indicator_parabolic_sar narrowed)',
    'Petrifying': 'generic',
    'Positive Directional': 'covered by indicator_dmi',
    'Positive and Negative': 'generic',
    'Price': 'generic',
    'Pure Price': 'generic',
    'Rally\\nMarket Type\\nThis': 'truncation noise',
    'Ratio': 'generic',
    'Retracement Osc': 'garbled, unverified',
    'Rijun Sen': 'garbled Kijun Sen; covered by indicator_ichimoku_kijun',
    'Rounded\\nBottom\\nThis': 'already in catalog (chart_rounded_bottom)',
    'S-H-S': 'head-and-shoulders, already covered',
    'SIMPLE BUT EFFECTIVE\\nThis': 'truncation noise',
    'Sell': 'generic',
    'Sharp Momentum': 'generic',
    'Shooting star': 'already in catalog (candlestick_shooting_star)',
    'Shoulders Bottom': 'head-and-shoulders, already covered',
    'Spike': 'generic',
    'Straight': 'generic',
    'Their': 'pronoun, noise',
    'Trade Management The Butterfly': 'already in catalog (harmonic_butterfly)',
    'Trend\\nThis Donchian Trend': 'already in catalog',
    'Triangle': 'already in catalog (chart_triangle)',
    'Triple Moving Average\\nThis': 'truncation noise',
    'UK Open The': 'truncation noise',
    'Ulis': 'unverified',
    'Unemployment': 'macro, noise',
    'Visual Dictionary': 'generic',
    'Volume': 'generic',
    'Wall Street powerhouses': 'noise',
    'Warning': 'generic',
    'Wedge': 'already in catalog (chart_wedge)',
    'Whatever': 'generic',
    'Whichever': 'generic',
    'Wide': 'generic',
    'Your': 'pronoun, noise',
}

# Turtle Soup approved separately (mined as lowercase)
APPROVED['turtle soup'] = dict(mid='strategy_turtle_soup', name='Turtle Soup',
                               parent='failed_breakout_reentry', mclass='other')
# OBV / VFI / DMI already added above; add remaining approved extras
APPROVED['obv'] = APPROVED.get('obv') or dict(mid='indicator_on_balance_volume', name='OBV',
                                               parent='volume_confirmed_breakout', mclass='indicator_method')
APPROVED['vfi'] = APPROVED.get('vfi') or dict(mid='indicator_volume_flow', name='Volume Flow Indicator',
                                              parent='volume_confirmed_breakout', mclass='indicator_method')
APPROVED['dmi'] = APPROVED.get('dmi') or dict(mid='indicator_dmi', name='DMI',
                                              parent='trend_continuation_pullback', mclass='indicator_method')

if __name__ == '__main__':
    import json, os
    out = {
        'stage': 'A2.2',
        'approved': APPROVED,
        'rejected': REJECTED,
        'approved_count': len(APPROVED),
    }
    base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    with open(os.path.join(base, 'registry', 'p4_a22_approval.json'), 'w') as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
    print(f"approved: {len(APPROVED)}")
    for k in sorted(APPROVED):
        print(f"  {k:28s} -> {APPROVED[k]['mid']:40s} [{APPROVED[k]['mclass']}] parent={APPROVED[k]['parent']}")
    print(f"rejected: {len(REJECTED)}")
